<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>常见的内置错误</title>
</head>

<body>




    <script>
        /*

        目标: 进一步理解 JS 中的错误 (Error) 和错误处理

        1. 错误的类型
            Error: 所有的错误的类型
            ReferenceError: 引用的变量不存在
            TypeError: 数据类型不正确的错误
            RangeError: 数据值不在其所运行的范围内
            SyntaxError: 语法错误

        2. 错误处理
            捕获错误: try ... catch
            抛出错误: throw error

        3. 错误对象
            message 属性: 错误相关信息
            stack 属性: 函数调用栈记录信息

        */





        // 1. 常见的内置错误
        // 1).ReferenceError: 引用的变量不存在
        // console.log(a); // Uncaught ReferenceError: a is not defined

        console.log("----"); // 如果没有捕获或者处理上面的错误，这句代码就不会执行

        // 2).TypeError: 数据类型不正确的错误
        let b
        // console.log(b.xxx);// Uncaught TypeError: Cannot read property 'xxx' of undefined

        // 3).RangeError: 数据值不在其所允许的范围内
        function fn() {
            fn()
        }

        // fn() Uncaught RangeError: Maximum call stack size exceeded
        // 这里的fn() 属于递归调用，且没有结束条件会栈溢出，即超过数据的运行范围内

        // SynataxError: 语法错误
        // const c = """"  Uncaught SyntaxError: Unexpected string 语法错误


        //异常处理


        // 抛出错误: throw error

        function something() {
            if (Date.now() % 2 === 1) {

                console.log("当前时间为奇数，可以执行任务");
            } else {// 如果当前时间是偶数时抛出异常，由调用来处理
                throw new Error("当前时间为偶数，无法执行任务");
            }
        }


        // 捕获处理异常

        try {

            something()
        } catch (error) {
            alert(error.message);
        }




    </script>


</body>

</html>